/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.*;
import javax.swing.*;
import java.nio.file.Path;
import java.nio.file.Paths;
/**
 *
 * @author ADMIN
 */
public class FrameMenu extends javax.swing.JFrame {
    
    Path currentRelativePath = Paths.get("");
    String s = currentRelativePath.toAbsolutePath().toString();
    
    static public int stile_scacchiera=1;
    static public int livello_volume = 50;
    
    public final String percorso_effetto_menu = s+"\\src\\hitclap.wav";
    public final String percorso_effetto_opzioni = s+"\\src\\hitclap2.wav";
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
        MenuOpzioni.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuMain = new javax.swing.JPanel();
        buttonScacchi = new javax.swing.JLabel();
        buttonMenuGioca = new javax.swing.JButton();
        buttonMenuOpzioni = new javax.swing.JButton();
        buttonMenuEsci = new javax.swing.JButton();
        buttonMenuPartitePrec = new javax.swing.JButton();
        separatorMeinMenu = new javax.swing.JSeparator();
        MenuOpzioni = new javax.swing.JPanel();
        labelOpzioni = new javax.swing.JLabel();
        buttonOpzioniEsci = new javax.swing.JButton();
        buttonFrecciaSxStili = new javax.swing.JButton();
        buttonFrecciaDxStili = new javax.swing.JButton();
        labelStili = new javax.swing.JLabel();
        buttonEliminaRisultati = new javax.swing.JButton();
        separatorOpzioni = new javax.swing.JSeparator();
        sliderVolume = new javax.swing.JSlider();
        labelVolume0 = new javax.swing.JLabel();
        labelVolume50 = new javax.swing.JLabel();
        labelVolume100 = new javax.swing.JLabel();
        labelOpzioniVolume = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scacchi");
        setResizable(false);

        MenuMain.setBackground(new java.awt.Color(255, 255, 255));

        buttonScacchi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scacchi_text.png"))); // NOI18N

        buttonMenuGioca.setBackground(new java.awt.Color(188, 140, 99));
        buttonMenuGioca.setText("Gioca");
        buttonMenuGioca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottoneEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottoneEsci(evt);
            }
        });
        buttonMenuGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuGiocaActionPerformed(evt);
            }
        });

        buttonMenuOpzioni.setBackground(new java.awt.Color(133, 94, 66));
        buttonMenuOpzioni.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenuOpzioni.setText("Opzioni");
        buttonMenuOpzioni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottoneEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottoneEsci(evt);
            }
        });
        buttonMenuOpzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListenerApriOpzioni(evt);
            }
        });

        buttonMenuEsci.setBackground(new java.awt.Color(133, 94, 66));
        buttonMenuEsci.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenuEsci.setText("Esci :)");
        buttonMenuEsci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottoneEntraTriste(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottoneEsciTriste(evt);
            }
        });
        buttonMenuEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuEsciActionPerformed(evt);
            }
        });

        buttonMenuPartitePrec.setBackground(new java.awt.Color(188, 140, 99));
        buttonMenuPartitePrec.setText("Partite precedenti");
        buttonMenuPartitePrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottoneEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottoneEsci(evt);
            }
        });

        javax.swing.GroupLayout MenuMainLayout = new javax.swing.GroupLayout(MenuMain);
        MenuMain.setLayout(MenuMainLayout);
        MenuMainLayout.setHorizontalGroup(
            MenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMainLayout.createSequentialGroup()
                .addGroup(MenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuMainLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(MenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonMenuEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonMenuOpzioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonMenuGioca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonMenuPartitePrec, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGroup(MenuMainLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(buttonScacchi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addComponent(separatorMeinMenu)
        );
        MenuMainLayout.setVerticalGroup(
            MenuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonScacchi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorMeinMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonMenuGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMenuOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMenuPartitePrec, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(buttonMenuEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        MenuOpzioni.setBackground(new java.awt.Color(255, 255, 255));
        MenuOpzioni.setPreferredSize(new java.awt.Dimension(600, 400));
        MenuOpzioni.setVisible(false);

        labelOpzioni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opzioni_text.png"))); // NOI18N
        labelOpzioni.setPreferredSize(new java.awt.Dimension(155, 50));

        buttonOpzioniEsci.setBackground(new java.awt.Color(188, 140, 99));
        buttonOpzioniEsci.setText("Esci");
        buttonOpzioniEsci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottoneEntraTriste(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottoneEsciTriste(evt);
            }
        });
        buttonOpzioniEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsciOpzioni(evt);
            }
        });

        buttonFrecciaSxStili.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frecciasx.png"))); // NOI18N
        buttonFrecciaSxStili.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonFrecciaSxStili.setBorderPainted(false);
        buttonFrecciaSxStili.setContentAreaFilled(false);
        buttonFrecciaSxStili.setFocusPainted(false);
        buttonFrecciaSxStili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premi_frecciasx(evt);
            }
        });

        buttonFrecciaDxStili.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frecciadx.png"))); // NOI18N
        buttonFrecciaDxStili.setBorderPainted(false);
        buttonFrecciaDxStili.setContentAreaFilled(false);
        buttonFrecciaDxStili.setFocusPainted(false);
        buttonFrecciaDxStili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premi_frecciadx(evt);
            }
        });

        labelStili.setFont(new java.awt.Font("Calibri Light", 0, 40)); // NOI18N
        labelStili.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStili.setText("Classico");

        buttonEliminaRisultati.setText("Elimina risultati delle partite");
        buttonEliminaRisultati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaRisPartite(evt);
            }
        });

        sliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Imposta_livello_volume(evt);
            }
        });

        labelVolume0.setText("0");
        labelVolume0.setToolTipText("");

        labelVolume50.setText("50");

        labelVolume100.setText("100");

        labelOpzioniVolume.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        labelOpzioniVolume.setText("Volume:");

        javax.swing.GroupLayout MenuOpzioniLayout = new javax.swing.GroupLayout(MenuOpzioni);
        MenuOpzioni.setLayout(MenuOpzioniLayout);
        MenuOpzioniLayout.setHorizontalGroup(
            MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorOpzioni, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(MenuOpzioniLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(labelOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                        .addComponent(buttonOpzioniEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                        .addComponent(buttonEliminaRisultati, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                        .addComponent(labelOpzioniVolume)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                        .addComponent(buttonFrecciaSxStili, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelStili, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonFrecciaDxStili, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                        .addGroup(MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuOpzioniLayout.createSequentialGroup()
                                .addGroup(MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOpzioniLayout.createSequentialGroup()
                                        .addComponent(labelVolume50)
                                        .addGap(106, 106, 106))
                                    .addGroup(MenuOpzioniLayout.createSequentialGroup()
                                        .addComponent(labelVolume0, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(labelVolume100)))
                        .addGap(151, 151, 151))))
        );
        MenuOpzioniLayout.setVerticalGroup(
            MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOpzioniLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separatorOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFrecciaSxStili, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStili)
                    .addComponent(buttonFrecciaDxStili, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(buttonEliminaRisultati, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelOpzioniVolume)
                .addGap(4, 4, 4)
                .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuOpzioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVolume0)
                    .addComponent(labelVolume50)
                    .addComponent(labelVolume100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(buttonOpzioniEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottoneEntra
        // TODO add your handling code here:
        JButton bottone = (JButton)evt.getSource();
        bottone.setBounds(bottone.getLocation().x-7, bottone.getLocation().y-7, bottone.getSize().width+14, bottone.getSize().height+14);
        RiproduciEffetto(percorso_effetto_menu);

        
    }//GEN-LAST:event_BottoneEntra

    private void BottoneEsci(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottoneEsci
        // TODO add your handling code here:
        JButton bottone = (JButton)evt.getSource();
        bottone.setBounds(bottone.getLocation().x+7, bottone.getLocation().y+7, bottone.getSize().width-14, bottone.getSize().height-14);

    }//GEN-LAST:event_BottoneEsci

    private void buttonMenuEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuEsciActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonMenuEsciActionPerformed

    private void BottoneEntraTriste(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottoneEntraTriste
        // TODO add your handling code here:
        JButton bottone = (JButton)evt.getSource();      
        //bottone.setText("Esci :(");
        bottone.setBounds(bottone.getLocation().x-7, bottone.getLocation().y-7, bottone.getSize().width+14, bottone.getSize().height+14);
        RiproduciEffetto(percorso_effetto_menu);

    }//GEN-LAST:event_BottoneEntraTriste

    private void BottoneEsciTriste(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottoneEsciTriste
        // TODO add your handling code here:
        JButton bottone = (JButton)evt.getSource();
        bottone.setBounds(bottone.getLocation().x+7, bottone.getLocation().y+7, bottone.getSize().width-14, bottone.getSize().height-14);
        //bottone.setText("Esci :)");        
    }//GEN-LAST:event_BottoneEsciTriste

    private void ListenerApriOpzioni(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListenerApriOpzioni
        // TODO add your handling code here:
        MenuMain.setVisible(false);
        MenuOpzioni.setVisible(true);
    }//GEN-LAST:event_ListenerApriOpzioni

    private void buttonMenuGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuGiocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenuGiocaActionPerformed

    private void EsciOpzioni(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsciOpzioni
        // TODO add your handling code here:
        MenuOpzioni.setVisible(false);
        MenuMain.setVisible(true);
    }//GEN-LAST:event_EsciOpzioni

    private void premi_frecciadx(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premi_frecciadx
        // TODO add your handling code here:
        if(stile_scacchiera==3)
            stile_scacchiera = 1;
        
        else
            stile_scacchiera = stile_scacchiera +1;
        
        imposta_stile();
        RiproduciEffetto(percorso_effetto_opzioni);

    }//GEN-LAST:event_premi_frecciadx

    private void premi_frecciasx(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premi_frecciasx
        // TODO add your handling code here:
        
        if(stile_scacchiera==1)
            stile_scacchiera = 3;
        
        else
            stile_scacchiera = stile_scacchiera -1;
        
        imposta_stile();
        RiproduciEffetto(percorso_effetto_opzioni);
    }//GEN-LAST:event_premi_frecciasx

    private void EliminaRisPartite(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaRisPartite
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Lista delle partite precedenti pulita con successo", "Operazione effettuata", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_EliminaRisPartite

    private void Imposta_livello_volume(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Imposta_livello_volume
        // TODO add your handling code here:
        livello_volume = sliderVolume.getValue();
        
    }//GEN-LAST:event_Imposta_livello_volume
    
    public static void cambia_volume(Clip clip){
    
        FloatControl control = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
        float range = control.getMinimum();
        float result = range * (1 - livello_volume / 100.0f);
        control.setValue(result);
        
    }
    
    private void imposta_stile(){
        
        if(stile_scacchiera == 1)
            labelStili.setText("Classico");
        
        else if(stile_scacchiera == 2)
            labelStili.setText("Anni 60");
        
        else
            labelStili.setText("Moderno");
                                                                                            
    }
    
    public static void RiproduciEffetto(String percorso){
    
        
     
        try{
            
            File file = new File(percorso);
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(file));
            
            cambia_volume(clip);
            
            clip.start();
            
        }catch(Exception e){
                
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                FrameMenu f = new FrameMenu();
                
                f.setVisible(true);
                f.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuMain;
    private javax.swing.JPanel MenuOpzioni;
    private javax.swing.JButton buttonEliminaRisultati;
    private javax.swing.JButton buttonFrecciaDxStili;
    private javax.swing.JButton buttonFrecciaSxStili;
    private javax.swing.JButton buttonMenuEsci;
    private javax.swing.JButton buttonMenuGioca;
    private javax.swing.JButton buttonMenuOpzioni;
    private javax.swing.JButton buttonMenuPartitePrec;
    private javax.swing.JButton buttonOpzioniEsci;
    private javax.swing.JLabel buttonScacchi;
    private javax.swing.JLabel labelOpzioni;
    private javax.swing.JLabel labelOpzioniVolume;
    private javax.swing.JLabel labelStili;
    private javax.swing.JLabel labelVolume0;
    private javax.swing.JLabel labelVolume100;
    private javax.swing.JLabel labelVolume50;
    private javax.swing.JSeparator separatorMeinMenu;
    private javax.swing.JSeparator separatorOpzioni;
    private javax.swing.JSlider sliderVolume;
    // End of variables declaration//GEN-END:variables
}
